<!-- javascripts -->
<script src="assets/backend/js/jquery.js"></script>
<script src="assets/backend/js/jquery-ui-1.10.4.min.js"></script>
<script src="assets/backend/js/jquery-1.8.3.min.js"></script>
<script src="assets/backend/js/jquery-ui-1.9.2.custom.min.js"></script>
<!-- bootstrap -->
<script src="assets/backend/js/bootstrap.min.js"></script>
<!-- nice scroll -->
<script src="assets/backend/js/jquery.scrollTo.min.js"></script>
<script src="assets/backend/js/jquery.nicescroll.js"></script>
<!-- charts scripts -->
<script src="assets/backend/assets/jquery-knob/js/jquery.knob.js"></script>
<script src="assets/backend/js/jquery.sparkline.js"></script>
<script src="assets/backend/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
<script src="assets/backend/js/owl.carousel.js"></script>
<!-- jQuery full calendar -->
<script src="assets/backend/js/fullcalendar.min.js"></script>
<!-- Full Google Calendar - Calendar -->
<script src="assets/backend/assets/fullcalendar/fullcalendar/fullcalendar.js"></script>
<!--script for this page only-->
<script src="assets/backend/js/calendar-custom.js"></script>
<script src="assets/backend/js/jquery.rateit.min.js"></script>
<!-- custom select -->
<script src="assets/backend/js/jquery.customSelect.min.js"></script>
<script src="assets/backend/assets/chart-master/Chart.js"></script>
<!-- custom script for this page-->
<script src="assets/backend/js/sparkline-chart.js"></script>
<script src="assets/backend/js/easy-pie-chart.js"></script>
<script src="assets/backend/js/jquery-jvectormap-1.2.2.min.js"></script>
<script src="assets/backend/js/jquery-jvectormap-world-mill-en.js"></script>
<script src="assets/backend/js/xcharts.min.js"></script>
<script src="assets/backend/js/jquery.autosize.min.js"></script>
<script src="assets/backend/js/jquery.placeholder.min.js"></script>
<script src="assets/backend/js/gdp-data.js"></script>
<script src="assets/backend/js/morris.min.js"></script>
<script src="assets/backend/js/sparklines.js"></script>
<script src="assets/backend/js/charts.js"></script>
<script src="assets/backend/js/jquery.slimscroll.min.js"></script>
<!--custom checkbox & radio-->
<script src="assets/backend/js/ga.js"></script>
<!--custom switch-->
<script src="assets/backend/js/bootstrap-switch.js"></script>
<!--custom tagsinput-->
<script src="assets/backend/js/jquery.tagsinput.js"></script>
<!-- bootstrap-wysiwyg -->
<script src="assets/backend/js/jquery.hotkeys.js"></script>
<script src="assets/backend/js/bootstrap-wysiwyg.js"></script>
<script src="assets/backend/js/bootstrap-wysiwyg-custom.js"></script>
<script src="assets/backend/js/moment.js"></script>
<script src="assets/backend/js/bootstrap-colorpicker.js"></script>
<script src="assets/backend/js/daterangepicker.js"></script>
<script src="assets/backend/js/bootstrap-datepicker.js"></script>
<!-- ck editor -->
<script src="assets/backend/assets/ckeditor/ckeditor.js"></script>
<!-- custom form component script for this page-->
<script src="assets/backend/js/form-component.js"></script>
<!-- jquery validate js -->
<script type="text/javascript" src="assets/backend/js/jquery.validate.min.js"></script>
<!-- custom form validation script for this page-->
<script src="assets/backend/js/form-validation-script.js"></script>
<!-- custome script for all page -->
<script src="assets/backend/js/scripts.js"></script>
<!-- gritter -->
<!-- custom gritter script for this page only-->
<script src="assets/backend/js/gritter.js" type="text/javascript"></script>
