<!DOCTYPE html>
<html lang="en" />
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Favicons -->
    <link rel="icon" href="assets/frontend/img/favicon.png" />
    <link rel="apple-touch-icon" href="assets/frontend/img/apple-touch-icon.png" />
    <title><?= $title; ?></title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="assets/backend/css/bootstrap.min.css" />
    <!-- bootstrap theme -->
    <link rel="stylesheet" href="assets/backend/css/bootstrap-theme.css" />
    <!--external css-->
    <!-- font icon -->
    <link rel="stylesheet" href="assets/backend/css/elegant-icons-style.css" />
    <link rel="stylesheet" href="assets/backend/css/font-awesome.min.css" />

    <!-- full calendar css-->
    <link rel="stylesheet" href="assets/backend/assets/fullcalendar/fullcalendar/bootstrap-fullcalendar.css" />
    <link rel="stylesheet" href="assets/backend/assets/fullcalendar/fullcalendar/fullcalendar.css" />
    <!-- easy pie chart-->
    <link rel="stylesheet" href="assets/backend/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" />
    <!-- owl carousel -->
    <link rel="stylesheet" href="assets/backend/css/owl.carousel.css" type="text/css" />
    <link rel="stylesheet" href="assets/backend/css/jquery-jvectormap-1.2.2.css" />
    <link rel="stylesheet" href="assets/backend/css/fullcalendar.css" />
    <link rel="stylesheet" href="assets/backend/css/widgets.css" />
    <link rel="stylesheet" href="assets/backend/css/xcharts.min.css" rel=" stylesheet" />
    <link rel="stylesheet" href="assets/backend/css/jquery-ui-1.10.4.min.css" />
    <link rel="stylesheet" href="assets/backend/css/daterangepicker.css" />
    <link rel="stylesheet" href="assets/backend/css/bootstrap-datepicker.css" />
    <link rel="stylesheet" href="assets/backend/css/bootstrap-colorpicker.css" />

    <!-- Custom styles -->
    <link rel="stylesheet" href="<?= asset('assets/backend/css/style.css'); ?>" />
    <link rel="stylesheet" href="<?= asset('assets/backend/css/style-responsive.css'); ?>" />
    <link rel="stylesheet" href="<?= asset('assets/backend/css/custom.css'); ?>" />
</head>
