<aside>
    <div id="sidebar" class="nav-collapse ">
        <ul class="sidebar-menu">
            <li class="active">
                <a class="" href="dashboard.php">
                    <i class="icon_house_alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="icon_desktop"></i>
                    <span>Patient</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub">
                    <li><a class="" href="add-patient.php">Add Patient</a></li>
                    <li><a class="" href="patients.php">Patients</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="icon_desktop"></i>
                    <span>Donor</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub">
                    <li><a class="" href="donors.php?validated=no">Donor Requests</a></li>
                    <li><a class="" href="donors.php?validated=yes">Approved Donors</a></li>
                </ul>
            </li>
            <li class="sub-menu">
                <a href="javascript:;" class="">
                    <i class="icon_desktop"></i>
                    <span>Donation</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub">
                    <li><a class="" href="donate.php">Donate Blood</a></li>
                    <li><a class="" href="donations.php">Donations</a></li>
                </ul>
            </li>
            <li>
                <a class="" href="messages.php">
                    <i class="icon_plus"></i>
                    <span>Messages</span>
                </a>
            </li>
            <li>
                <a class="" href="register.php">
                    <i class="icon_plus"></i>
                    <span>Register</span>
                </a>
            </li>
            <li>
                <a class="" href="logout.php">
                    <i class="icon_plus"></i>
                    <span>Logout</span>
                </a>
            </li>
            <li class="sub-menu hide">
                <a href="javascript:;" class="">
                    <i class="icon_document_alt"></i>
                    <span>Pages</span>
                    <span class="menu-arrow arrow_carrot-right"></span>
                </a>
                <ul class="sub">
                    <li><a class="" href="widgets.php">Widgets</a></li>
                    <li><a class="" href="form_component.php">Form Elements</a></li>
                    <li><a class="" href="form_validation.php">Form Validation</a></li>
                    <li><a class="" href="general.php">Elements</a></li>
                    <li><a class="" href="buttons.php">Buttons</a></li>
                    <li><a class="" href="grids.php">Grids</a></li>
                </ul>
            </li>
        </ul>
    </div>
</aside>
